FROM node:19-alpine3.15 as build

WORKDIR /app

COPY . /app/

RUN yarn

ARG BASE_URL
ENV VITE_APP_BASE_URL=$BASE_URL

RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.23.2-alpine

COPY --from=build /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]